---
title: "Gee model"
subtitle: "Resistance data"
author: "Yiming Wang"
date: 08/12/2021
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Learning material and Required packages
## Learning material
```{r learning, echo=TRUE,message=FALSE, warning=FALSE,message=FALSE, warning=FALSE}
 # https://data.library.virginia.edu/getting-started-with-generalized-estimating-equations/
 # https://stats.idre.ucla.edu/r/dae/logit-regression/ ## Odds ratio
 # https://stackoverflow.com/questions/11461382/error-in-fitting-a-model-with-gee-na-nan-inf-in-foreign-function-call-arg-3 ## error 
 # https://stat.ethz.ch/pipermail/r-help/2006-April/103372.html ## P-value
 # https://sakai.unc.edu/access/content/group/2842013b-58f5-4453-aa8d-3e01bacbfc3d/public/Ecol562_Spring2012/docs/lectures/lecture23.htm ## correlation structure
  ## The last argument, corstr, allows us to specify the correlation structure within groups (id).
    ### "independence": the observations within the groups are uncorrelated.Apparently, samples within the id are independent, so choose this one
    ### "exchangeable": each pair of observations in a group has the same correlation.
    ### "unstructured": each pair of observations in a group is allowed to have a different correlation.
    ### "AR-M": this is used to fit an autoregressive structure. To obtain a specific autoregressive structure requires the additional argument Mv. For example corstr="AR-M", Mv=1 yields an AR(1) structure, while corstr="AR-M", Mv=2 yields an AR(2) structure.
    ### "non_stat_M_dep": stands for nonstationary M-dependent and generates a banded correlation matrix. It also requires the Mv argument to denote the number of nonzero off-diagonal bands that are to be estimated. Like "AR-M", "non_stat_M_dep" assumes there is a natural order to the data. Like "unstructured", "non_stat_M_dep" allows the entries within the each nonzero band to be different. As an example corstr="non_stat_M_dep", Mv=1 would correspond to the following correlation matrix for a group of size 4. Here α, β, and γ are parameters that need to be estimated.
```


## Load Packages
```{r Load packages, echo=TRUE,message=FALSE, warning=FALSE}
pacman::p_load(
  readxl,
  dplyr,
  data.table,
  writexl,
  gee
)
```

# Import and shape data
## Import data to R
```{r Import data, echo=TRUE,message=FALSE, warning=FALSE,message=FALSE, warning=FALSE}

setwd("D:/My backup disk/Things currently working on/AZM+SERPAT/Submission_Chest_2021") #Windows
# setwd("/Volumes/Yiming Wang/My backup disk/Things currently working on/AZM+SERPAT/Final of the final/Data analysis") #Mac
data_all <- read_excel("transmission coding.xlsx")

```

## Shape data to factor
```{r Shape data, echo=TRUE,message=FALSE, warning=FALSE,message=FALSE, warning=FALSE}
head(data_all)
# Convert the data to factor
cols <- c("ID", "Sample_ID","Group_ID","ermA","ermB","ermC","ermF","mef","msrA","msrE","tetM","tetO","tetW","PermA","PermB","PermC","PermF","Pmef","PmsrA","PmsrE","PtetM","PtetO","PtetW")
data_shape <- lapply(data_all[cols], as.factor) %>% data.frame()

data_shape$ID <-as.numeric(data_shape$ID)


# Select data you wanted from the whole data table
data_shape_Macrolide <- data_shape %>% 
  filter(Group_ID == "Macrolide")
data_shape_Nomacrolide <- data_shape %>% 
  filter(Group_ID == "No_macrolide")
```

# GEE_whether patient carried the gene and whether macrolides exposure affect close contacts carried the gene

## ermA gene
```{r ermA, echo=TRUE,message=FALSE, warning=FALSE,message=FALSE, warning=FALSE, error=TRUE}
# Run GEE model
## ID here has to be a number and need to convert to numeric value as the id argument specifies the grouping factor. In this case it’s the “id” column in the data frame.
## Corstr choose independence here as the correlation structure within groups (id) is independent
ermA_gee <- gee(ermA ~ PermA + Group_ID,
                data = data_all, 
                id = ID, 
                family = binomial,
                corstr = "independence")
# Summarize the model
summary(ermA_gee)

```

## ermB gene
```{r ermB, echo=TRUE,message=FALSE, warning=FALSE,message=FALSE, warning=FALSE, error=TRUE}
# Run GEE model
## ID here has to be a number and need to convert to numeric value as the id argument specifies the grouping factor. In this case it’s the “id” column in the data frame.
## Corstr choose independence here as the correlation structure within groups (id) is independent
ermB_gee <- gee(ermB ~ PermB + Group_ID,
                data = data_all, 
                id = ID, 
                family = binomial,
                corstr = "independence")
# Summarize the model
summary(ermB_gee)

# Calculate the P vlaues using a normal approxiamtion for the distribution of z
P_ermB <- 2 * pnorm(abs(coef(summary(ermB_gee))[,5]), lower.tail = FALSE)
P_ermB

# Extract the fixed-effect coefficients for odds ratio
coef <- coef(summary(ermB_gee))
coef

coef_PermB <- coef[2,1]
coef_ermB_macrolide <- coef[3,1]

# Extract Robust SE for yielding 95% CIs expressed on the odds scale
se_PermB <- coef[2,4]
se_PermB

se_ermB_macrolide <- coef[3,4]
se_ermB_macrolide

# odds ratios and 95% CI
## odds ratio
exp(coef_PermB)
exp(coef_ermB_macrolide)
## 95% CI
exp(coef(ermB_gee)["PermB"]+c(-1,1)*se_PermB*qnorm(0.975))
exp(coef(ermB_gee)["Group_IDNo_macrolide"]+c(-1,1)*se_PermB*qnorm(0.975))
## combine odds ratio and 95% CI
exp(cbind("Odds ratio" = coef(ermB_gee)["PermB"], coef(ermB_gee)["PermB"]+c(-1,1)*se_PermB*qnorm(0.975)))
exp(cbind("Odds ratio" = coef(ermB_gee)["Group_IDNo_macrolide"], coef(ermB_gee)["Group_IDNo_macrolide"]+c(-1,1)*se_ermB_macrolide*qnorm(0.975)))
```

## ermC gene
```{r ermC, echo=TRUE,message=FALSE, warning=FALSE,message=FALSE, warning=FALSE, error=TRUE}
# Run GEE model
## ID here has to be a number and need to convert to numeric value as the id argument specifies the grouping factor. In this case it’s the “id” column in the data frame.
## Corstr choose independence here as the correlation structure within groups (id) is independent
ermC_gee <- gee(ermC ~ PermC + Group_ID,
                data = data_all, 
                id = ID, 
                family = binomial,
                corstr = "independence")
# Summarize the model
summary(ermC_gee)

# Calculate the P vlaues using a normal approxiamtion for the distribution of z
P_ermC <- 2 * pnorm(abs(coef(summary(ermC_gee))[,5]), lower.tail = FALSE)
P_ermC

# Extract the fixed-effect coefficients for odds ratio
coef <- coef(summary(ermC_gee))
coef

coef_PermC <- coef[2,1]
coef_ermC_macrolide <- coef[3,1]

# Extract Robust SE for yielding 95% CIs expressed on the odds scale
se_PermC <- coef[2,4]
se_PermC

se_ermC_macrolide <- coef[3,4]
se_ermC_macrolide

# odds ratios and 95% CI
## odds ratio
exp(coef_PermC)
exp(coef_ermC_macrolide)
## 95% CI
exp(coef(ermC_gee)["PermC"]+c(-1,1)*se_PermC*qnorm(0.975))
exp(coef(ermC_gee)["Group_IDNo_macrolide"]+c(-1,1)*se_PermC*qnorm(0.975))
## combine odds ratio and 95% CI
exp(cbind("Odds ratio" = coef(ermC_gee)["PermC"], coef(ermC_gee)["PermC"]+c(-1,1)*se_PermC*qnorm(0.975)))
exp(cbind("Odds ratio" = coef(ermC_gee)["Group_IDNo_macrolide"], coef(ermC_gee)["Group_IDNo_macrolide"]+c(-1,1)*se_ermC_macrolide*qnorm(0.975)))

```

## ermF gene
```{r ermF, echo=TRUE,message=FALSE, warning=FALSE,message=FALSE, warning=FALSE, error=TRUE}
# Run GEE model
## ID here has to be a number and need to convert to numeric value as the id argument specifies the grouping factor. In this case it’s the “id” column in the data frame.
## Corstr choose independence here as the correlation structure within groups (id) is independent
ermF_gee <- gee(ermF ~ PermF + Group_ID,
                data = data_all, 
                id = ID, 
                family = binomial,
                corstr = "independence")
# Summarize the model
summary(ermF_gee)

# Calculate the P vlaues using a normal approxiamtion for the distribution of z
P_ermF <- 2 * pnorm(abs(coef(summary(ermF_gee))[,5]), lower.tail = FALSE)
P_ermF

# Extract the fixed-effect coefficients for odds ratio
coef <- coef(summary(ermF_gee))
coef

coef_PermF <- coef[2,1]
coef_ermF_macrolide <- coef[3,1]

# Extract Robust SE for yielding 95% CIs expressed on the odds scale
se_PermF <- coef[2,4]
se_PermF

se_ermF_macrolide <- coef[3,4]
se_ermF_macrolide

# odds ratios and 95% CI
## odds ratio
exp(coef_PermF)
exp(coef_ermF_macrolide)
## 95% CI
exp(coef(ermF_gee)["PermF"]+c(-1,1)*se_PermF*qnorm(0.975))
exp(coef(ermF_gee)["Group_IDNo_macrolide"]+c(-1,1)*se_PermF*qnorm(0.975))
## combine odds ratio and 95% CI
exp(cbind("Odds ratio" = coef(ermF_gee)["PermF"], coef(ermF_gee)["PermF"]+c(-1,1)*se_PermF*qnorm(0.975)))
exp(cbind("Odds ratio" = coef(ermF_gee)["Group_IDNo_macrolide"], coef(ermF_gee)["Group_IDNo_macrolide"]+c(-1,1)*se_ermF_macrolide*qnorm(0.975)))
```

## mef gene
```{r mef, echo=TRUE,message=FALSE, warning=FALSE,message=FALSE, warning=FALSE, error=TRUE}
# Run GEE model
## ID here has to be a number and need to convert to numeric value as the id argument specifies the grouping factor. In this case it’s the “id” column in the data frame.
## Corstr choose independence here as the correlation structure within groups (id) is independent
mef_gee <- gee(mef ~ Pmef + Group_ID,
                data = data_all, 
                id = ID, 
                family = binomial,
                corstr = "independence")
# Summarize the model
summary(mef_gee)

# Calculate the P vlaues using a normal approxiamtion for the distribution of z
P_mef <- 2 * pnorm(abs(coef(summary(mef_gee))[,5]), lower.tail = FALSE)
P_mef

# Extract the fixed-effect coefficients for odds ratio
coef <- coef(summary(mef_gee))
coef

coef_Pmef <- coef[2,1]
coef_mef_macrolide <- coef[3,1]

# Extract Robust SE for yielding 95% CIs expressed on the odds scale
se_Pmef <- coef[2,4]
se_Pmef

se_mef_macrolide <- coef[3,4]
se_mef_macrolide

# odds ratios and 95% CI
## odds ratio
exp(coef_Pmef)
exp(coef_mef_macrolide)
## 95% CI
exp(coef(mef_gee)["Pmef"]+c(-1,1)*se_Pmef*qnorm(0.975))
exp(coef(mef_gee)["Group_IDNo_macrolide"]+c(-1,1)*se_Pmef*qnorm(0.975))
## combine odds ratio and 95% CI
exp(cbind("Odds ratio" = coef(mef_gee)["Pmef"], coef(mef_gee)["Pmef"]+c(-1,1)*se_Pmef*qnorm(0.975)))
exp(cbind("Odds ratio" = coef(mef_gee)["Group_IDNo_macrolide"], coef(mef_gee)["Group_IDNo_macrolide"]+c(-1,1)*se_mef_macrolide*qnorm(0.975)))

```


## msrA gene
```{r msrA, echo=TRUE,message=FALSE, warning=FALSE,message=FALSE, warning=FALSE, error=TRUE}
# Run GEE model
## ID here has to be a number and need to convert to numeric value as the id argument specifies the grouping factor. In this case it’s the “id” column in the data frame.
## Corstr choose independence here as the correlation structure within groups (id) is independent
msrA_gee <- gee(msrA ~ PmsrA + Group_ID,
                data = data_all, 
                id = ID, 
                family = binomial,
                corstr = "independence")
# Summarize the model
summary(msrA_gee)

# Calculate the P vlaues using a normal approxiamtion for the distribution of z
P_msrA <- 2 * pnorm(abs(coef(summary(msrA_gee))[,5]), lower.tail = FALSE)
P_msrA

# Extract the fixed-effect coefficients for odds ratio
coef <- coef(summary(msrA_gee))
coef

coef_PmsrA <- coef[2,1]
coef_msrA_macrolide <- coef[3,1]

# Extract Robust SE for yielding 95% CIs expressed on the odds scale
se_PmsrA <- coef[2,4]
se_PmsrA

se_msrA_macrolide <- coef[3,4]
se_msrA_macrolide

# odds ratios and 95% CI
## odds ratio
exp(coef_PmsrA)
exp(coef_msrA_macrolide)
## 95% CI
exp(coef(msrA_gee)["PmsrA"]+c(-1,1)*se_PmsrA*qnorm(0.975))
exp(coef(msrA_gee)["Group_IDNo_macrolide"]+c(-1,1)*se_PmsrA*qnorm(0.975))
## combine odds ratio and 95% CI
exp(cbind("Odds ratio" = coef(msrA_gee)["PmsrA"], coef(msrA_gee)["PmsrA"]+c(-1,1)*se_PmsrA*qnorm(0.975)))
exp(cbind("Odds ratio" = coef(msrA_gee)["Group_IDNo_macrolide"], coef(msrA_gee)["Group_IDNo_macrolide"]+c(-1,1)*se_msrA_macrolide*qnorm(0.975)))
```

## msrE gene
```{r msrE, echo=TRUE,message=FALSE, warning=FALSE,message=FALSE, warning=FALSE, error=TRUE}
# Run GEE model
## ID here has to be a number and need to convert to numeric value as the id argument specifies the grouping factor. In this case it’s the “id” column in the data frame.
## Corstr choose independence here as the correlation structure within groups (id) is independent
msrE_gee <- gee(msrE ~ PmsrE + Group_ID,
                data = data_all, 
                id = ID, 
                family = binomial,
                corstr = "independence")
# Summarize the model
summary(msrE_gee)

# Calculate the P vlaues using a normal approxiamtion for the distribution of z
P_msrE <- 2 * pnorm(abs(coef(summary(msrE_gee))[,5]), lower.tail = FALSE)
P_msrE

# Extract the fixed-effect coefficients for odds ratio
coef <- coef(summary(msrE_gee))
coef

coef_PmsrE <- coef[2,1]
coef_msrE_macrolide <- coef[3,1]

# Extract Robust SE for yielding 95% CIs expressed on the odds scale
se_PmsrE <- coef[2,4]
se_PmsrE

se_msrE_macrolide <- coef[3,4]
se_msrE_macrolide

# odds ratios and 95% CI
## odds ratio
exp(coef_PmsrE)
exp(coef_msrE_macrolide)
## 95% CI
exp(coef(msrE_gee)["PmsrE"]+c(-1,1)*se_PmsrE*qnorm(0.975))
exp(coef(msrE_gee)["Group_IDNo_macrolide"]+c(-1,1)*se_PmsrE*qnorm(0.975))
## combine odds ratio and 95% CI
exp(cbind("Odds ratio" = coef(msrE_gee)["PmsrE"], coef(msrE_gee)["PmsrE"]+c(-1,1)*se_PmsrE*qnorm(0.975)))
exp(cbind("Odds ratio" = coef(msrE_gee)["Group_IDNo_macrolide"], coef(msrE_gee)["Group_IDNo_macrolide"]+c(-1,1)*se_msrE_macrolide*qnorm(0.975)))
```

## tetM gene
```{r tetM, echo=TRUE,message=FALSE, warning=FALSE,message=FALSE, warning=FALSE, error=TRUE}
# Run GEE model
## ID here has to be a number and need to convert to numeric value as the id argument specifies the grouping factor. In this case it’s the “id” column in the data frame.
## Corstr choose independence here as the correlation structure within groups (id) is independent
tetM_gee <- gee(tetM ~ PtetM + Group_ID,
                data = data_all, 
                id = ID, 
                family = binomial,
                corstr = "independence")
# Summarize the model
summary(tetM_gee)

# Calculate the P vlaues using a normal approxiamtion for the distribution of z
P_tetM <- 2 * pnorm(abs(coef(summary(tetM_gee))[,5]), lower.tail = FALSE)
P_tetM

# Extract the fixed-effect coefficients for odds ratio
coef <- coef(summary(tetM_gee))
coef

coef_PtetM <- coef[2,1]
coef_tetM_macrolide <- coef[3,1]

# Extract Robust SE for yielding 95% CIs expressed on the odds scale
se_PtetM <- coef[2,4]
se_PtetM

se_tetM_macrolide <- coef[3,4]
se_tetM_macrolide

# odds ratios and 95% CI
## odds ratio
exp(coef_PtetM)
exp(coef_tetM_macrolide)
## 95% CI
exp(coef(tetM_gee)["PtetM"]+c(-1,1)*se_PtetM*qnorm(0.975))
exp(coef(tetM_gee)["Group_IDNo_macrolide"]+c(-1,1)*se_PtetM*qnorm(0.975))
## combine odds ratio and 95% CI
exp(cbind("Odds ratio" = coef(tetM_gee)["PtetM"], coef(tetM_gee)["PtetM"]+c(-1,1)*se_PtetM*qnorm(0.975)))
exp(cbind("Odds ratio" = coef(tetM_gee)["Group_IDNo_macrolide"], coef(tetM_gee)["Group_IDNo_macrolide"]+c(-1,1)*se_tetM_macrolide*qnorm(0.975)))
```

## tetO gene
```{r tetO, echo=TRUE,message=FALSE, warning=FALSE,message=FALSE, warning=FALSE, error=TRUE}
# Run GEE model
## ID here has to be a number and need to convert to numeric value as the id argument specifies the grouping factor. In this case it’s the “id” column in the data frame.
## Corstr choose independence here as the correlation structure within groups (id) is independent
tetO_gee <- gee(tetO ~ PtetO + Group_ID,
                data = data_all, 
                id = ID, 
                family = binomial,
                corstr = "independence")
# Summarize the model
summary(tetO_gee)

# Calculate the P vlaues using a normal approxiamtion for the distribution of z
P_tetO <- 2 * pnorm(abs(coef(summary(tetO_gee))[,5]), lower.tail = FALSE)
P_tetO

# Extract the fixed-effect coefficients for odds ratio
coef <- coef(summary(tetO_gee))
coef

coef_PtetO <- coef[2,1]
coef_tetO_macrolide <- coef[3,1]

# Extract Robust SE for yielding 95% CIs expressed on the odds scale
se_PtetO <- coef[2,4]
se_PtetO

se_tetO_macrolide <- coef[3,4]
se_tetO_macrolide

# odds ratios and 95% CI
## odds ratio
exp(coef_PtetO)
exp(coef_tetO_macrolide)
## 95% CI
exp(coef(tetO_gee)["PtetO"]+c(-1,1)*se_PtetO*qnorm(0.975))
exp(coef(tetO_gee)["Group_IDNo_macrolide"]+c(-1,1)*se_PtetO*qnorm(0.975))
## combine odds ratio and 95% CI
exp(cbind("Odds ratio" = coef(tetO_gee)["PtetO"], coef(tetO_gee)["PtetO"]+c(-1,1)*se_PtetO*qnorm(0.975)))
exp(cbind("Odds ratio" = coef(tetO_gee)["Group_IDNo_macrolide"], coef(tetO_gee)["Group_IDNo_macrolide"]+c(-1,1)*se_tetO_macrolide*qnorm(0.975)))
```


## tetW gene
```{r tetW, echo=TRUE,message=FALSE, warning=FALSE,message=FALSE, warning=FALSE, error=TRUE}
# Run GEE model
## ID here has to be a number and need to convert to numeric value as the id argument specifies the grouping factor. In this case it’s the “id” column in the data frame.
## Corstr choose independence here as the correlation structure within groups (id) is independent
tetW_gee <- gee(tetW ~ PtetW + Group_ID,
                data = data_all, 
                id = ID, 
                family = binomial,
                corstr = "independence")
# Summarize the model
summary(tetW_gee)

# Calculate the P vlaues using a normal approxiamtion for the distribution of z
P_tetW <- 2 * pnorm(abs(coef(summary(tetW_gee))[,5]), lower.tail = FALSE)
P_tetW

# Extract the fixed-effect coefficients for odds ratio
coef <- coef(summary(tetW_gee))
coef

coef_PtetW <- coef[2,1]
coef_tetW_macrolide <- coef[3,1]

# Extract Robust SE for yielding 95% CIs expressed on the odds scale
se_PtetW <- coef[2,4]
se_PtetW

se_tetW_macrolide <- coef[3,4]
se_tetW_macrolide

# odds ratios and 95% CI
## odds ratio
exp(coef_PtetW)
exp(coef_tetW_macrolide)
## 95% CI
exp(coef(tetW_gee)["PtetW"]+c(-1,1)*se_PtetW*qnorm(0.975))
exp(coef(tetW_gee)["Group_IDNo_macrolide"]+c(-1,1)*se_PtetW*qnorm(0.975))
## combine odds ratio and 95% CI
exp(cbind("Odds ratio" = coef(tetW_gee)["PtetW"], coef(tetW_gee)["PtetW"]+c(-1,1)*se_PtetW*qnorm(0.975)))
exp(cbind("Odds ratio" = coef(tetW_gee)["Group_IDNo_macrolide"], coef(tetW_gee)["Group_IDNo_macrolide"]+c(-1,1)*se_tetW_macrolide*qnorm(0.975)))
```

